python runBert.py \
		--is_training \
		--per_gpu_batch_size 1 --per_gpu_test_batch_size 80 \
		--bert_model ../outputs/output1 \
		--dataset_script_dir ../data_scripts \
		--dataset_cache_dir /tmp/negs_tutorial_cache \
		--log_path ../logs/log_finetune.txt \
		--train_file /home/dou/replearn/anchors-master/data/train \
		--dev_file  /home/dou/replearn/anchors-master/data/dev/all.json \
		--dev_id_file /home/dou/replearn/anchors-master/data/dev/ids.tsv \
		--msmarco_score_file_path ./score_bert.txt \
		--msmarco_dev_qrel_path /home/dou/replearn//anchors-master/data/msmarco/msmarco-docdev-qrels.tsv \
		--save_path ../outputs/output_finetune
